version: "3"
services:
  my-mongodb:
    image: mongo:5.0.6
    environment:
      - MONGO_INITDB_DATABASE=test
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - "27017:27017"
    restart: always
  my-rest-app:
    build: .
    ports:
      - "9090:9090"
    restart: always
    depends_on:
      - my-mongodb
